plugins:
  upcoming_events_enabled:
    default: false
    client: true

  upcoming_events_limit:
    default: 5
    client: true
  
  upcoming_events_featured_cfa:
    default: ""
    client: true

  upcoming_events_featured_caia:
    default: ""
    client: true

  upcoming_events_featured_frm:
    default: ""
    client: true
